### ISSUE TITLE
Add feature to get info of remote github(or other git) repo.

### ISSUE THREAD

**Issue by voxelin** [o2sh/onefetch#854] opened 2022-11-08 17:44 UTC
### Summary 💡

Feature needs to parse .git repo (e.g https://github.com/voxelin/voxelTG.git) and return info of it. (Also can realise with github API)

**Comment by spenserblack** [comment] 2022-11-08 19:20
@voxelin If you could give an example of what you want to see, that might help clear up misunderstandings.

e.g.
```
...
Last change: 5 days ago
Repo: https://github.com/foo/fork
Remotes:
         origin (https://github.com/foo/fork.git)
         upstream (https://github.com/foo/bar.git)
Commits: 123
```
I'm just guessing what you mean by "info of remote github(or other git) repo"

Or do you mean like these: https://github.com/o2sh/onefetch/issues/351 https://github.com/o2sh/onefetch/issues/63 https://github.com/o2sh/onefetch/issues/24

(I'm going to make a label like `Blocked: Network Dependence` because i'ts getting kind of hard to dig up these requests :laughing:)

**Comment by voxelin** [comment] 2022-11-09 08:39
Hi, I meant something like getting info of remote repo, without actually cloning it.
![image](https://user-images.githubusercontent.com/78281477/200781144-99d83b71-2a8a-4b57-b823-7c9d00b5830c.png)

I think it can be done calling github API or smth

**Comment by spenserblack** [comment] 2022-11-09 13:25
Thanks for clearing that up! [We probably won't use the API](https://github.com/o2sh/onefetch/issues/63#issuecomment-539234924).

I think this issue is a duplicate of https://github.com/o2sh/onefetch/issues/419
I'm not 100% against fetching a remote repo, but I don't know if the work is worth the reward when it's [pretty easy to just clone it yourself](https://gist.github.com/spenserblack/4214c81d146a9fd93b71f6c28dc6075f).

**Closed** 2022-11-11 19:41 UTC
Labels: feature request
