### ISSUE TITLE
Fennel support

### ISSUE THREAD

**Issue by reo101** [o2sh/onefetch#875] opened 2022-11-28 08:50 UTC
### Language Name 🖊

Fennel

---

https://fennel-lang.org/

Fennel is a lisp that compiles to Lua

### Logo 📷

https://git.sr.ht/~technomancy/fennel-lang.org/blob/main/logo.svg

can be seen here: https://fennel-lang.org/

### Upstream support ✅

- [X] Does tokei already support the language in question?

**Comment by spenserblack** [comment] 2022-11-28 18:34
Duplicate of #578

While Fennel is in tokei's source code, tokei hasn't had a release with that addition, as far as I know. https://docs.rs/tokei/latest/tokei/enum.LanguageType.html

**Closed by spenserblack** 2022-11-28 18:34 UTC
Labels: enhancement, good first issue

**Comment by p00f** [comment] 2023-11-22 06:41
Tokei now has an alpha release with fennel support: https://crates.io/crates/tokei/13.0.0-alpha.0
