### ISSUE TITLE
onefetch Crash Report

### ISSUE THREAD

**Issue by kurisunoob** [o2sh/onefetch#1360] opened 2024-07-05 02:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Crash
![2024-07-05 10-58-54-39](https://github.com/o2sh/onefetch/assets/29200000/a7516705-ece7-481e-b17d-edc656c11dc0)

**Comment by spenserblack** [comment] 2024-07-05 19:36
Thanks for reporting! I'm going to close this in favor of https://github.com/o2sh/onefetch/issues/1306. You should be able to find all relevant conversation, including the cause, workarounds, and next steps that we can do.

**Closed by spenserblack** 2024-07-05 19:36 UTC
Labels: bug
